### ISSUE TITLE
Ajout du manifeste "Culturel"

### ISSUE THREAD

**Issue by Mallouestan** [Association-Mallouestan/Mallouestan#12]

**Comment by LauTbk** [comment]
#Squelette du manifeste 

- ##Pb 
Art=industrie, élististe, coupé du réel, focus sur le résultat, pouvoir décisionnel sur légitimité  par une minorité d'individus
- ##Conséquences 
cloisonnement social, rupture vie/art, perte de capacités créatives et réflexives, perte de capacité à l'écoute de soi,peu de place et de temps à l'essai, binarité réussite/échec
- ##Causes
société capitaliste (focus résultat donc argent avec réduction de temps), société de consommation et d'instantanéité (peu de place à la réflexion et initiative créative), société compétitive (performance, résultat attendu, apparence), entre soi dans l'art (cloisonnement et rupture avec le réel), décrédibilisation du statut d'artiste (renforce l'entre soi), art sans autre utilité que divertissement (pas d'intérêt pour le processus, attente de résultat)
- ##Solution 
Donner du temps et de la valeur aux processus et essais, créer des contextes d'échanges et de partage, donner la possibilté à toustes de proposer, valoriser le potentiel créatif de moments non-identifiés comme artistiques (sortir de la case art et déborder partout)
- ##Action
S'organiser pour trouver du temps pour l'exploration (temps libres, ateliers, discussion, rédaction ...)
Organiser des événements (présentation d'un projet élaboré, d'une ébauche, d'une idée)
Se donner un rôle actif d'oeil extérieur (retours, critiques, remarques...) 
Disposer d'espaces et de matériel propices à la pratique de différents médiums (instruments, salle poly, peinture, supports d'écriture) 
Disposer de ressources pour la documentation et l'inspiration (livres, ordinateur, musiques)

**Comment by Mallouestan** [comment]
Je l'ajoute en tant que fichiers
